### ISSUE TITLE
Unprotected read of 16-bit internal register

### ISSUE THREAD

**Issue by mikaelpatel** [rlogiacco/VoltageReference#1]
The read of the ADC registers is not protected. An interrupt may corrupt the value. 
https://github.com/rlogiacco/VoltageReference/blob/master/VoltageReference.cpp#L48

The read should be atomic i.e. use CLI/SEI.

**Comment by rlogiacco** [comment]
I'm not sure about corruptability of the second register. By reading http://web.ics.purdue.edu/~jricha14/Port_Stuff/PortA_ADC.htm and in particular the section regarding ADCL and ADCH, the section states:
_The result of the ADC conversion is stored in these two registers.  Once ADCL is read, the ADC Data Register will not update again until ADCH is read.  If using only 8 bit precision, it is sufficient to just read ADCH.  Otherwise, ADCL must be read first._

This would imply there is an internal protection of the registers.

Can you provide any reference against this?

**Comment by rlogiacco** [comment]
closing due to lack of feedback
