### ISSUE TITLE
Wiring A0

### ISSUE THREAD

**Issue by vallettea** [rlogiacco/VoltageReference#2]
Hello,

thanks for this very useful lib.
I don't get if I should connect A0 to the battery directly to the battery in order to monitor battery level ?
Besides, should I distinguish between normal voltage and when it is bellow 1V each using the two piece of code you provide in the example ?

Thanks

**Comment by rlogiacco** [comment]
No, `A0` goes to the analog voltage you want to read.

This library is **NOT** intended to monitor a battery level or anything like that, I have another library for that purpose called `BatterySense`.

This library instead is intended to improve the precision of your analog readings when you are not using an external voltage reference.

I mention a battery in the `README` only to provide one of the many examples when this library can be useful.

When reading voltages below 1V you can use the `ONE VOLT` internal reference rather than the calibrated one.
